### ISSUE TITLE
Discuss: Move Abort Ongoing Requests button from bridge editor to request page

### ISSUE THREAD

**Issue by angeljruiz** [williampj/bridgeapi.js#41]
The AOR button in the actions dialog on the bridge editor page seems out of place. Everything on the editor page deals with the bridge itself, while the AOR button relates more to the bridge's events. Personally, if I were looking for that button, I'd look on the requests page first.

**Comment by andrewc910** [comment]
I agree i would look at the requests page. I think the idea was ongoing requests would show an abort button for that single request. The bridge page would show an abort all. I am open to ongoing requests showing both an abort this request and an abort all button. However, I don't think completed requests should show either button.

**Comment by angeljruiz** [comment]
I was going to implement a `abort all events` button next to the `abort current event` button but I couldn't figure out how to do so without looping through the events again, which seems overkill. Gonna close for now
